# Generated by Django 4.1.3 on 2023-11-15 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dueño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', models.CharField(max_length=200)),
                ('apellido_materno', models.CharField(max_length=200)),
                ('nombres', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('motivo_de_visita', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Dueño',
                'verbose_name_plural': 'Dueños',
                'db_table': 'dueño',
                'ordering': ['apellido_paterno', '-apellido_materno'],
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('edad', models.CharField(max_length=20)),
                ('fecha_de_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=10)),
                ('dueño', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appfutbolista.dueño')),
            ],
        ),
    ]
